const Types = {
  CHARACTERS_LIST_REQUEST: '@characters/CHARACTERS_LIST_REQUEST',
  CHARACTERS_LIST_SUCCESS: '@characters/CHARACTERS_LIST_SUCCESS',
  CHARACTERS_LIST_FAILURE: '@characters/CHARACTERS_LIST_FAILURE',
};

export default Types;
